name: Upload

on:
  push:
    branches: [ main ]

jobs:
  upload_levels:
    runs-on: ubuntu-latest
    name: Upload levels
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy levels to S3
        uses: prewk/s3-cp-action@v2
        with:
          aws_s3_endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: './Levels'
          dest: 's3://s3.bf3reality.com/assets/customlevelloader'
          flags: --recursive
